# Generated by Django 4.0.3 on 2022-04-03 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('mentor', 'mentor')], default='user', max_length=10)),
                ('userReputation', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('creditAmount', models.PositiveIntegerField(default=5)),
                ('userDetails', models.TextField(max_length=1000, null=True)),
                ('userSkills', models.TextField(max_length=1000, null=True)),
                ('userInterests', models.TextField(max_length=1000, null=True)),
                ('userLocation', models.CharField(max_length=100)),
                ('userBadge', models.TextField(default='None', max_length=100, null=True)),
                ('userPicture', models.ImageField(default='male.png', null=True, upload_to='Profiles')),
                ('creditInprocess', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
