# Generated by Django 3.2.12 on 2022-04-04 09:22

from django.db import migrations, models
from django.core.management import call_command
fixture = 'initial_data'


def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label='sharity')


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userPicture',
            field=models.ImageField(default='/Profiles/male.png', null=True, upload_to='static/images/Profiles'),
        ),
    ]
