# Generated by Django 3.2.12 on 2022-04-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_profile_userpicture'),
        ('member', '0002_owner'),
    ]

    operations = [
    ]
