# Generated by Django 3.2.13 on 2022-05-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_profile_userpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='claims',
            field=models.TextField(default='[]', null=True),
        ),
    ]
