# Generated by Django 4.0.3 on 2022-05-08 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0006_offer_claims'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('noteID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('noteContent', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read')], default='Unread', max_length=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receiverID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiverID', to=settings.AUTH_USER_MODEL)),
                ('serviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer')),
            ],
        ),
    ]
