# Generated by Django 3.2.13 on 2022-05-28 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_offer_end_date'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='serviceID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.offer'),
        ),
    ]
