# Generated by Django 3.2.13 on 2022-06-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_serviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='noteContent',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read')], default='Unread', max_length=1000),
        ),
    ]
