# Generated by Django 3.2.13 on 2022-05-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
