# Generated by Django 3.2.13 on 2022-05-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermessages', '0002_alter_usermessage_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='usermessages.usermessage'),
        ),
    ]
