# Generated by Django 3.2.13 on 2022-05-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_profile_userlocation'),
        ('usermessages', '0004_auto_20220510_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='message_to',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='message_to',
            field=models.ManyToManyField(related_name='receiver', to='member.Profile'),
        ),
    ]
