# Generated by Django 3.2.13 on 2022-05-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_profile_userlocation'),
        ('usermessages', '0005_auto_20220510_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message_to',
            field=models.ManyToManyField(related_name='recipients', to='member.Profile'),
        ),
    ]
