# Generated by Django 3.2.13 on 2022-05-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_profile_userlocation'),
        ('usermessages', '0006_auto_20220511_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='is_read',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='is_read_by',
            field=models.ManyToManyField(related_name='seen', to='member.Profile'),
        ),
    ]
