# Generated by Django 3.2.13 on 2022-05-11 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermessages', '0007_auto_20220511_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='usermessages.usermessage'),
        ),
    ]
