# Generated by Django 3.2.13 on 2022-05-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermessages', '0010_alter_usermessage_inbox_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='inbox_owner',
        ),
    ]
