# Generated by Django 3.2.13 on 2022-06-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_profile_claims'),
        ('usermessages', '0012_userinbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinbox',
            name='content',
            field=models.ManyToManyField(blank=True, related_name='inbox_content', to='usermessages.UserMessage'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='usermessages.usermessage'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='is_read_by',
            field=models.ManyToManyField(blank=True, related_name='seen', to='member.Profile'),
        ),
    ]
