# Generated by Django 3.2.12 on 2022-04-04 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='service',
            name='credit',
        ),
        migrations.AddField(
            model_name='event',
            name='amendment_deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 13, 2, 16, 51657), verbose_name='Amendment deadline'),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='amendment_deadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 13, 2, 16, 51657), verbose_name='Amendment deadline'),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='duration'),
            preserve_default=False,
        ),
    ]
