# Generated by Django 3.2.12 on 2022-04-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20220404_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='amendment_deadline',
            field=models.DateTimeField(verbose_name='Amendment deadline'),
        ),
        migrations.AlterField(
            model_name='service',
            name='amendment_deadline',
            field=models.DateTimeField(verbose_name='Amendment deadline'),
        ),
    ]
