# Generated by Django 3.2.12 on 2022-04-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20220404_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/Offers'),
        ),
    ]
