# Generated by Django 3.2.13 on 2022-04-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_offer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='claims',
            field=models.TextField(default='[]', null=True),
        ),
    ]
