# Generated by Django 3.2.13 on 2022-05-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_offer_claims'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='End date'),
        ),
    ]
