# Generated by Django 3.2.13 on 2022-05-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_offer_claims'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='latitude',
            field=models.CharField(max_length=500, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='offer',
            name='longitude',
            field=models.CharField(max_length=500, null=True, verbose_name='Longitude'),
        ),
    ]
