# Generated by Django 3.2.13 on 2022-05-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20220514_1654'),
        ('offers', '0007_offer_end_date'),
    ]

    operations = [
    ]
