# Generated by Django 3.2.13 on 2022-06-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_merge_0007_auto_20220514_1654_0007_offer_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
