# Generated by Django 3.2.13 on 2022-05-22 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_profile_userpicture'),
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitybuilderbadge',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CBbadge', to='member.owner'),
        ),
        migrations.AlterField(
            model_name='greatserviceproviderbadge',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='GSPbadges', to='member.owner'),
        ),
        migrations.AlterField(
            model_name='mastereventorganizerbadge',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='MEObadges', to='member.owner'),
        ),
        migrations.AlterField(
            model_name='newcomerbadge',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Nbadges', to='member.owner'),
        ),
    ]
